runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /img
  static_dir: img

- url: /.*
  script: topdog.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
